"""your message

Revision ID: 0caab33f0767
Revises: 24cac39e6813
Create Date: 2024-06-28 21:03:21.893458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0caab33f0767'
down_revision = '24cac39e6813'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
